/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.imaster.misiontic2022.c2.reto4.view;

import co.edu.imaster.misiontic2022.c2.reto4.controller.ReportesController;
import co.edu.imaster.misiontic2022.c2.reto4.model.dao.ProyectoBancoDao;
import co.edu.imaster.misiontic2022.c2.reto4.model.vo.ComprasDeLiderVo;
import co.edu.imaster.misiontic2022.c2.reto4.model.vo.DeudasPorProyectoVo;
import co.edu.imaster.misiontic2022.c2.reto4.model.vo.ProyectoBancoVo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author USUARIO
 */
public class frmConstruccion extends javax.swing.JFrame {

    /**
     * Creates new form frmConstruccion
     */
    private ReportesController controlador;
    private ProyectoBancoDao bancos;
    private BancosTableModel tb;
    private ProyectosDeudoresTableModel deudoresTB;
    private GastosTableModel gastosTB;

    public frmConstruccion() {
        initComponents();
        setLocationRelativeTo(null);
        controlador = new ReportesController();
        bancos = new ProyectoBancoDao();
        cargarInformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tpContenedor = new javax.swing.JTabbedPane();
        pBancos = new javax.swing.JPanel();
        lbTituloBancos = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbConstructora = new javax.swing.JLabel();
        txtConstructora = new javax.swing.JTextField();
        lbCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lbClasificacion = new javax.swing.JLabel();
        txtClasificacion = new javax.swing.JTextField();
        lbEstrato = new javax.swing.JLabel();
        txtEstrato = new javax.swing.JTextField();
        lbLider = new javax.swing.JLabel();
        txtLider = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cmbBanco = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInformacion = new javax.swing.JTable();
        pDeudores = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDeudas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbOrdenamiento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        rdAsc = new javax.swing.JRadioButton();
        rdDesc = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtIDDeudor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDeuda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLiderD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnBuscarD = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pCompras = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbGastos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbOrdenamientoG = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        rdAscG = new javax.swing.JRadioButton();
        rdDescG = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        txtIDGasto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtLiderG = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnBuscarG = new javax.swing.JButton();
        spLimite = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mbNavegacion = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miBancos = new javax.swing.JMenuItem();
        miDeudores = new javax.swing.JMenuItem();
        miComprasLider = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto de Construccion");

        tpContenedor.setToolTipText("");
        tpContenedor.setName(""); // NOI18N

        pBancos.setLayout(new java.awt.BorderLayout());

        lbTituloBancos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTituloBancos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloBancos.setText("Proyectos Financiados Por Un Banco");
        pBancos.add(lbTituloBancos, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(300);

        lbID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbID.setText("ID del Proyecto:");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbConstructora.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbConstructora.setText("Constructora:");

        txtConstructora.setEditable(false);
        txtConstructora.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbCiudad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbCiudad.setText("Ciudad:");

        txtCiudad.setEditable(false);
        txtCiudad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbClasificacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbClasificacion.setText("Clasificación:");

        txtClasificacion.setEditable(false);
        txtClasificacion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbEstrato.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbEstrato.setText("Estrato");

        txtEstrato.setEditable(false);
        txtEstrato.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbLider.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbLider.setText("Lider");

        txtLider.setEditable(false);
        txtLider.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Banco");

        cmbBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbID)
                        .addGap(27, 27, 27)
                        .addComponent(txtID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbClasificacion)
                        .addGap(45, 45, 45)
                        .addComponent(txtClasificacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCiudad)
                        .addGap(78, 78, 78)
                        .addComponent(txtCiudad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbConstructora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtConstructora))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEstrato)
                            .addComponent(lbLider))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLider)
                            .addComponent(txtEstrato)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(cmbBanco, 0, 174, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbConstructora)
                    .addComponent(txtConstructora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCiudad)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbClasificacion)
                    .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstrato)
                    .addComponent(txtEstrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLider)
                    .addComponent(txtLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnBuscar)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        tbInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbInformacion);

        jSplitPane1.setRightComponent(jScrollPane1);

        pBancos.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        tpContenedor.addTab("Bancos", pBancos);

        pDeudores.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Proyectos con Deudas Vigentes");
        pDeudores.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jSplitPane3.setDividerLocation(460);

        tbDeudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbDeudas);

        jSplitPane3.setLeftComponent(jScrollPane3);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Limite de deuda:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Ordernar por:");

        cmbOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID del proyecto", "Valor", "Lider del proyecto" }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Orden: ");

        rdAsc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdAsc.setText("Ascendente");

        rdDesc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdDesc.setText("Descendente");

        txtIDDeudor.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("ID del proyecto:");

        txtDeuda.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Valor:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Lider:");

        txtLiderD.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Información");

        btnBuscarD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBuscarD.setText("Buscar");
        btnBuscarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbOrdenamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLimite)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdAsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(13, 13, 13))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDeuda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(txtIDDeudor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLiderD, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdDesc)
                    .addComponent(rdAsc))
                .addGap(20, 20, 20)
                .addComponent(btnBuscarD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIDDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtLiderD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Parametros de busqueda");
        jPanel3.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        jSplitPane3.setRightComponent(jPanel3);

        pDeudores.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        tpContenedor.addTab("Deudores", pDeudores);

        pCompras.setLayout(new java.awt.BorderLayout());

        jSplitPane4.setDividerLocation(460);

        tbGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbGastos);

        jSplitPane4.setLeftComponent(jScrollPane4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Limite de resultados:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Ordernar por:");

        cmbOrdenamientoG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID del proyecto", "Valor", "Lider del proyecto" }));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Orden: ");

        rdAscG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdAscG.setText("Ascendente");

        rdDescG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdDescG.setText("Descendente");

        txtIDGasto.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("ID del proyecto:");

        txtValor.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Valor:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Lider:");

        txtLiderG.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Información");

        btnBuscarG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBuscarG.setText("Buscar");
        btnBuscarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbOrdenamientoG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rdAscG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(rdDescG))
                    .addComponent(spLimite))
                .addGap(13, 13, 13))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(txtIDGasto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLiderG, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarG, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbOrdenamientoG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rdDescG)
                    .addComponent(rdAscG))
                .addGap(27, 27, 27)
                .addComponent(btnBuscarG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtIDGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtLiderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Parametros de busqueda");
        jPanel5.add(jLabel19, java.awt.BorderLayout.PAGE_START);

        jSplitPane4.setRightComponent(jPanel5);

        pCompras.add(jSplitPane4, java.awt.BorderLayout.CENTER);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Gastos de Lideres");
        pCompras.add(jLabel20, java.awt.BorderLayout.PAGE_START);

        tpContenedor.addTab("Compras", pCompras);

        getContentPane().add(tpContenedor, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Navegación");

        miBancos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miBancos.setText("Consulta por bancos");
        miBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBancosActionPerformed(evt);
            }
        });
        jMenu1.add(miBancos);

        miDeudores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miDeudores.setText("Proyectos deudores");
        miDeudores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeudoresActionPerformed(evt);
            }
        });
        jMenu1.add(miDeudores);

        miComprasLider.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miComprasLider.setText("Top compras por lider");
        miComprasLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miComprasLiderActionPerformed(evt);
            }
        });
        jMenu1.add(miComprasLider);

        mbNavegacion.add(jMenu1);

        setJMenuBar(mbNavegacion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBancosActionPerformed
        this.tpContenedor.setSelectedIndex(0);
    }//GEN-LAST:event_miBancosActionPerformed

    private void miDeudoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeudoresActionPerformed
        // TODO add your handling code here:
        this.tpContenedor.setSelectedIndex(1);
    }//GEN-LAST:event_miDeudoresActionPerformed

    private void miComprasLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miComprasLiderActionPerformed
        // TODO add your handling code here:
        this.tpContenedor.setSelectedIndex(2);
    }//GEN-LAST:event_miComprasLiderActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            var listaInicial = controlador.proyectosPorBanco(cmbBanco.getSelectedItem().toString());
            tb = new BancosTableModel(listaInicial);
            tbInformacion.setModel(tb);

        } catch (SQLException ex) {
            Logger.getLogger(frmConstruccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDActionPerformed
        cargarDatosTableDeudores();
    }//GEN-LAST:event_btnBuscarDActionPerformed

    private void btnBuscarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGActionPerformed
        cargarDatosTableGastos();
    }//GEN-LAST:event_btnBuscarGActionPerformed

    private void cargarInformacion() {
        cmbBanco.removeAllItems();
        limpiarCamposBancos();

        try {

            var lista = bancos.nombreBancos();

            lista.forEach(banco -> {
                cmbBanco.addItem(banco);
            });

            var listaInicial = controlador.proyectosPorBanco(cmbBanco.getItemAt(-1));
            var bancoTB = new BancosTableModel(listaInicial);
            tbInformacion.setModel(bancoTB);

            tbInformacion.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tbInformacion.getSelectionModel().addListSelectionListener((e) -> {
                var row = tbInformacion.getSelectedRow();
                if (row == -1) {
                    limpiarCamposBancos();
                } else {
                    var proyecto = tb.cargarProyecto(row);
                    cargarInformacionBancos(proyecto);
                }
            });

            buttonGroup1.add(rdAsc);
            buttonGroup1.add(rdDesc);
            
            buttonGroup2.add(rdAscG);
            buttonGroup2.add(rdDescG);

            deudoresTB = new ProyectosDeudoresTableModel();
            tbDeudas.setModel(deudoresTB);

            tbDeudas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            tbDeudas.getSelectionModel().addListSelectionListener((e) -> {
                var row = tbDeudas.getSelectedRow();
                if (row == -1) {
                    limpiarCamposBancos();
                } else {
                    var proyecto = deudoresTB.getProyecto(row);
                    cargarInformacionDeudas(proyecto);
                }
            });
            
            gastosTB = new GastosTableModel();
            tbGastos.setModel(gastosTB);
            
            tbGastos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            tbGastos.getSelectionModel().addListSelectionListener((e) -> {
                var row = tbGastos.getSelectedRow();
                if (row == -1) {
                    limpiarCamposBancos();
                } else {
                    var proyecto = gastosTB.getProyecto(row);
                    cargarInformacionGastos(proyecto);
                }
            });

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void limpiarCamposBancos() {
        txtID.setText("");
        txtCiudad.setText("");
        txtConstructora.setText("");
        txtClasificacion.setText("");
        txtEstrato.setText("");
        txtLider.setText("");

        txtIDDeudor.setText("");
        txtDeuda.setText("");
        txtLiderD.setText("");
        
        txtIDGasto.setText("");
        txtValor.setText("");
        txtLiderG.setText("");

    }

    public void cargarInformacionBancos(ProyectoBancoVo proyecto) {
        txtID.setText(String.valueOf(proyecto.getId()));
        txtCiudad.setText(proyecto.getCiudad());
        txtConstructora.setText(proyecto.getConstructora());
        txtClasificacion.setText(proyecto.getClasificacion());
        txtEstrato.setText(String.valueOf(proyecto.getEstrato()));
        txtLider.setText(proyecto.getLider());
    }

    public void cargarInformacionDeudas(DeudasPorProyectoVo proyecto) {
        txtIDDeudor.setText(String.valueOf(proyecto.getIdProyecto()));
        txtDeuda.setText(String.valueOf(proyecto.getValor()));
        txtLiderD.setText(proyecto.getLider());
    }
    
    public void cargarInformacionGastos(ComprasDeLiderVo proyecto) {
        txtIDGasto.setText(proyecto.getID());
        txtValor.setText(proyecto.getValor()+"");
        txtLiderG.setText(proyecto.getLider());
    }

    public void cargarDatosTableDeudores() {
        try {
            var limite = 0d;
            if (txtLimite.getText() != "" && txtLimite.getText() != null) {
                try {
                    limite = Double.parseDouble(txtLimite.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ha ingresa un fomato incorrecto.\nIngrese un número", "¡Fomato incompatible!", JOptionPane.ERROR_MESSAGE);
                }
            }

            if (limite >= 0) {

                var order = "";

                switch (cmbOrdenamiento.getSelectedIndex()) {
                    case 0:
                        order = "p.ID_Proyecto";
                        break;
                    case 1:
                        order = "VALOR";
                        break;
                    case 2:
                        order = "LIDER";
                        break;

                    default:
                        order = "p.ID_Proyecto";
                        break;
                }

                var fomr = "";

                if (rdDesc.isSelected()) {
                    fomr = "DESC";
                }
                if (rdAsc.isSelected()) {
                    fomr = "ASC";
                }

                var listaDeudas = controlador.deudas(limite, order, fomr);

                deudoresTB.llenarLista(listaDeudas);
                deudoresTB.fireTableDataChanged();
                
            }else{
                JOptionPane.showMessageDialog(null, "No se permiten valores negativos", "¡Fomato incompatible!", JOptionPane.ERROR_MESSAGE);
            }
            
            cmbOrdenamiento.setSelectedIndex(-1);
            rdAsc.setSelected(false);
            rdDesc.setSelected(false);
            txtLimite.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(frmConstruccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cargarDatosTableGastos() {
        try {
            var limite = (Integer) spLimite.getValue();
           
            if (limite != -1) {

                var order = "";

                switch (cmbOrdenamientoG.getSelectedIndex()) {
                    case 0:
                        order = "p.ID_Proyecto";
                        break;
                    case 1:
                        order = "VALOR";
                        break;
                    case 2:
                        order = "LIDER";
                        break;

                    default:
                        order = "p.ID_Proyecto";
                        break;
                }

                var fomr = "";

                if (rdDescG.isSelected()) {
                    fomr = "DESC";
                }
                if (rdAscG.isSelected()) {
                    fomr = "ASC";
                }

                var listaDeudas = controlador.compras(limite,order, fomr);

                gastosTB.llenarLista(listaDeudas);
                gastosTB.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(null, "No se permiten valores negativos", "¡Fomato incompatible!", JOptionPane.ERROR_MESSAGE);
            }
            
            cmbOrdenamientoG.setSelectedIndex(-1);
            rdAscG.setSelected(false);
            rdDescG.setSelected(false);
            spLimite.setValue((Integer)0);

        } catch (SQLException ex) {
            Logger.getLogger(frmConstruccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConstruccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConstruccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConstruccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConstruccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConstruccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarD;
    private javax.swing.JButton btnBuscarG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbBanco;
    private javax.swing.JComboBox<String> cmbOrdenamiento;
    private javax.swing.JComboBox<String> cmbOrdenamientoG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbClasificacion;
    private javax.swing.JLabel lbConstructora;
    private javax.swing.JLabel lbEstrato;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbLider;
    private javax.swing.JLabel lbTituloBancos;
    private javax.swing.JMenuBar mbNavegacion;
    private javax.swing.JMenuItem miBancos;
    private javax.swing.JMenuItem miComprasLider;
    private javax.swing.JMenuItem miDeudores;
    private javax.swing.JPanel pBancos;
    private javax.swing.JPanel pCompras;
    private javax.swing.JPanel pDeudores;
    private javax.swing.JRadioButton rdAsc;
    private javax.swing.JRadioButton rdAscG;
    private javax.swing.JRadioButton rdDesc;
    private javax.swing.JRadioButton rdDescG;
    private javax.swing.JSpinner spLimite;
    private javax.swing.JTable tbDeudas;
    private javax.swing.JTable tbGastos;
    private javax.swing.JTable tbInformacion;
    private javax.swing.JTabbedPane tpContenedor;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtConstructora;
    private javax.swing.JTextField txtDeuda;
    private javax.swing.JTextField txtEstrato;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDDeudor;
    private javax.swing.JTextField txtIDGasto;
    private javax.swing.JTextField txtLider;
    private javax.swing.JTextField txtLiderD;
    private javax.swing.JTextField txtLiderG;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

}
